export const colors = {
  background: '#1F1F24',
  card: '#2A2A32',
  line: '#393945',
  text: '#FFFFFF',
  muted: '#8A8A95',
  soft: '#C6C6CE',
  accent: '#9F2A67',
  accentHover: '#B8397A',
  badgeBg: '#7E2353',
  heroGlow: 'rgba(159,42,103,0.20)',
  errorText: '#9F2A67',
};

export const fonts = {
  body: 'Inter, system-ui, sans-serif',
};

export const sharedStyles = {
  container: {
    maxWidth: '1080px',
    px: { xs: 2, sm: 3 },
  },
  stepBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 1,
    bgcolor: colors.badgeBg,
    color: colors.text,
    fontSize: '0.6875rem',
    fontWeight: 800,
    letterSpacing: '0.05em',
    px: 1.5,
    py: 0.625,
    borderRadius: '6px',
  },
  stepLabel: {
    color: colors.accent,
    fontSize: '0.75rem',
    fontWeight: 700,
    letterSpacing: '0.06em',
    ml: 1.25,
  },
  primaryButton: {
    bgcolor: colors.accent,
    color: '#fff',
    borderRadius: '10px',
    px: 4,
    py: 2.25,
    fontSize: '1.0625rem',
    fontWeight: 800,
    letterSpacing: '0.02em',
    fontFamily: fonts.body,
    '&:hover': {
      bgcolor: colors.accentHover,
    },
    '&:disabled': {
      color: '#fff',
      opacity: 0.6,
    },
  },
  privacy: {
    mt: 0.5,
    textAlign: 'center',
    color: colors.muted,
    fontSize: '0.75rem',
  },
  exampleBadge: {
    fontSize: '0.5625rem',
    fontWeight: 800,
    letterSpacing: '0.05em',
    color: colors.accent,
    border: `1px solid ${colors.accent}`,
    borderRadius: '5px',
    px: 0.75,
    py: 0.375,
  },
  textField: {
    '& .MuiFormLabel-root': {
      color: colors.soft,
      fontSize: '0.875rem',
      fontWeight: 700,
    },
    '& .MuiOutlinedInput-root': {
      bgcolor: colors.card,
      color: colors.text,
      borderRadius: '8px',
      fontSize: '1rem',
      '& fieldset': {
        borderColor: colors.line,
      },
      '&:hover fieldset': {
        borderColor: colors.accent,
      },
      '&.Mui-focused fieldset': {
        borderColor: colors.accent,
        borderWidth: 2,
      },
      '&.Mui-error fieldset': {
        borderColor: colors.errorText,
      },
    },
    '& .MuiSvgIcon-root': {
      color: colors.muted,
    },
    '& .MuiFormHelperText-root': {
      mx: 0,
      mt: 0.5,
      color: colors.muted,
      fontSize: '0.75rem',
    },
  },
};

export const pageStyles = {
  root: {
    minHeight: '100vh',
    width: '100%',
    overflowX: 'hidden',
    bgcolor: colors.background,
    color: colors.text,
    fontFamily: fonts.body,
  },
  nav: {
    position: 'sticky',
    top: 0,
    zIndex: 50,
    bgcolor: colors.background,
    borderBottom: `1px solid ${colors.line}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    px: { xs: 2, sm: 3 },
    py: 1.75,
    gap: 2,
    flexWrap: 'wrap',
  },
  brandRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 1.25,
  },
  logoIcon: {
    position: 'relative',
    width: 36,
    height: 36,
    borderRadius: '8px',
    flexShrink: 0,
    overflow: 'hidden',
  },
  wordmark: {
    fontWeight: 800,
    fontSize: '1.125rem',
    color: colors.text,
  },
  wordmarkSub: {
    fontWeight: 500,
    color: colors.muted,
    fontSize: '0.875rem',
  },
  navCta: {
    bgcolor: colors.accent,
    color: '#fff',
    fontWeight: 700,
    fontSize: '0.875rem',
    px: 2.5,
    py: 1.25,
    borderRadius: '8px',
    textDecoration: 'none',
    '&:hover': {
      bgcolor: colors.accentHover,
    },
  },
  heroSection: {
    background: `radial-gradient(circle at top right, ${colors.heroGlow} 0%, rgba(31,31,36,0) 55%)`,
    pt: { xs: 6, sm: 9 },
    pb: { xs: 5, sm: 7 },
    px: { xs: 2, sm: 3 },
  },
  heroInner: {
    maxWidth: '880px',
    mx: 'auto',
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 2.75,
  },
  heroBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 1,
    border: `1px solid ${colors.line}`,
    color: colors.muted,
    fontSize: '0.75rem',
    fontWeight: 700,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    px: 2,
    py: 1,
    borderRadius: '999px',
  },
  heroBadgeDot: {
    width: 6,
    height: 6,
    borderRadius: '50%',
    bgcolor: colors.accent,
    flexShrink: 0,
  },
  heroTitle: {
    fontWeight: 900,
    fontSize: { xs: '1.875rem', sm: '2.5rem', md: '3.25rem' },
    lineHeight: 1.15,
    m: 0,
  },
  heroSubtitle: {
    fontWeight: 500,
    fontSize: { xs: '1rem', sm: '1.25rem' },
    lineHeight: 1.6,
    color: colors.soft,
    m: 0,
    maxWidth: '640px',
  },
  painList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 1,
    alignItems: 'flex-start',
    maxWidth: '520px',
    width: '100%',
    mt: 0.5,
  },
  painItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 1.25,
  },
  painItemIcon: {
    color: colors.accent,
    fontWeight: 700,
  },
  painItemText: {
    color: colors.soft,
    fontSize: '0.875rem',
  },
  heroCta: {
    ...sharedStyles.primaryButton,
    mt: 1,
    textDecoration: 'none',
    display: 'inline-block',
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: {
      xs: 'repeat(2, minmax(0, 1fr))',
      sm: 'repeat(4, minmax(0, 1fr))',
    },
    gap: 1.75,
    width: '100%',
    maxWidth: '820px',
    mt: 3,
  },
  statCard: {
    bgcolor: colors.card,
    border: `1px solid ${colors.line}`,
    borderRadius: '14px',
    px: 2,
    py: 2.5,
  },
  statNum: {
    fontWeight: 900,
    fontSize: '1.625rem',
    color: colors.accent,
  },
  statLabel: {
    fontSize: '0.75rem',
    color: colors.muted,
    mt: 0.75,
    lineHeight: 1.4,
  },
  logoBarSection: {
    pt: 4,
    pb: 1,
    px: { xs: 2, sm: 3 },
  },
  logoBarLabel: {
    color: colors.muted,
    fontSize: '0.6875rem',
    fontWeight: 700,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    textAlign: 'center',
    mb: 2.5,
  },
  logoStrip: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 4,
  },
  logoChip: {
    color: colors.soft,
    fontWeight: 700,
    fontSize: '0.9375rem',
    opacity: 0.7,
  },
  section: {
    py: { xs: 6, sm: 8 },
    px: { xs: 2, sm: 3 },
  },
  sectionTitle: {
    fontWeight: 800,
    fontSize: { xs: '1.5rem', sm: '2rem' },
    color: colors.text,
    mt: 2,
    mb: 0.5,
  },
  sectionSubtitle: {
    color: colors.muted,
    fontSize: '0.8125rem',
    fontStyle: 'italic',
    mb: 4,
  },
  caseGrid: {
    display: 'grid',
    gridTemplateColumns: {
      xs: '1fr',
      sm: 'repeat(3, minmax(0, 1fr))',
    },
    gap: 2.5,
  },
  caseCard: {
    position: 'relative',
    bgcolor: colors.card,
    border: `1px solid ${colors.line}`,
    borderRadius: '14px',
    p: 3.5,
    textAlign: 'center',
  },
  caseBadge: {
    position: 'absolute',
    top: 14,
    right: 14,
  },
  caseIcon: {
    fontSize: '1.75rem',
  },
  caseTitle: {
    fontWeight: 700,
    color: colors.text,
    mt: 1.25,
  },
  caseValue: {
    color: colors.accent,
    fontWeight: 700,
    fontSize: '1.125rem',
    mt: 0.5,
  },
  quoteLabel: {
    color: colors.muted,
    fontSize: '0.75rem',
    fontWeight: 700,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    textAlign: 'center',
    mt: 7,
    mb: 3,
  },
  testimonialGrid: {
    display: 'grid',
    gridTemplateColumns: {
      xs: '1fr',
      sm: 'repeat(3, minmax(0, 1fr))',
    },
    gap: 2.5,
  },
  testimonialCard: {
    position: 'relative',
    bgcolor: colors.card,
    border: `1px solid ${colors.line}`,
    borderRadius: '14px',
    p: 3.25,
  },
  testimonialQuote: {
    color: colors.text,
    fontSize: '0.9375rem',
    fontStyle: 'italic',
    lineHeight: 1.6,
    mb: 2,
  },
  testimonialName: {
    color: colors.text,
    fontWeight: 700,
    fontSize: '0.875rem',
  },
  testimonialRole: {
    color: colors.muted,
    fontSize: '0.8125rem',
    mt: 0.25,
  },
  methodologyNote: {
    maxWidth: '680px',
    mx: 'auto',
    textAlign: 'center',
    color: colors.muted,
    fontSize: '0.9375rem',
    lineHeight: 1.6,
    mt: 5,
  },
  footer: {
    px: { xs: 2, sm: 3 },
    py: 5,
    borderTop: `1px solid ${colors.line}`,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 2,
    textAlign: 'center',
  },
  footerLinks: {
    display: 'flex',
    gap: 2.5,
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  footerLink: {
    color: colors.muted,
    fontSize: '0.8125rem',
    textDecoration: 'none',
    '&:hover': {
      color: colors.text,
    },
  },
  footerMuted: {
    color: colors.muted,
    fontSize: '0.8125rem',
  },
  toast: {
    position: 'fixed',
    bottom: 24,
    left: '50%',
    transform: 'translateX(-50%)',
    bgcolor: colors.card,
    border: `1px solid ${colors.accent}`,
    color: colors.text,
    fontWeight: 600,
    fontSize: '0.875rem',
    px: 2.75,
    py: 1.75,
    borderRadius: '10px',
    zIndex: 100,
    animation: 'toastIn 0.3s ease',
  },
};

export const calculatorStyles = {
  card: {
    maxWidth: '1080px',
    mx: 'auto',
    mt: 2,
    bgcolor: colors.card,
    border: `1px solid ${colors.line}`,
    borderRadius: '20px',
    p: { xs: 3, sm: 5 },
  },
  cardTitle: {
    fontWeight: 800,
    fontSize: { xs: '1.375rem', sm: '1.625rem' },
    color: colors.text,
    m: 0,
    mb: 0.75,
  },
  cardSubtitle: {
    color: colors.muted,
    fontSize: '0.8125rem',
    mb: 3.5,
  },
  inputsGrid: {
    display: 'grid',
    gridTemplateColumns: {
      xs: '1fr',
      sm: 'repeat(auto-fit, minmax(280px, 1fr))',
    },
    gap: 2.5,
  },
  inputLabel: {
    display: 'block',
    fontWeight: 700,
    fontSize: '0.875rem',
    color: colors.soft,
    mb: 0.75,
  },
  inputHelper: {
    mt: 0.75,
    fontSize: '0.75rem',
    color: colors.muted,
  },
  staleWarning: {
    mt: 2.25,
    bgcolor: colors.background,
    border: `1px solid ${colors.accent}`,
    color: colors.accent,
    fontSize: '0.8125rem',
    fontWeight: 600,
    px: 1.75,
    py: 1.25,
    borderRadius: '8px',
  },
  calculateButton: {
    ...sharedStyles.primaryButton,
    mt: 3.5,
    width: '100%',
  },
  resultsCard: {
    maxWidth: '1080px',
    mx: 'auto',
    mt: 3,
    bgcolor: colors.card,
    border: `1px solid ${colors.line}`,
    borderRadius: '20px',
    p: { xs: 3, sm: 5 },
    animation: 'fadeInUp 0.5s ease',
  },
  resultsTitle: {
    fontWeight: 800,
    fontSize: '1.25rem',
    color: colors.text,
    textAlign: 'center',
    m: 0,
    mb: 2.5,
  },
  resultsGrid: {
    display: 'grid',
    gridTemplateColumns: {
      xs: '1fr',
      sm: 'repeat(2, minmax(0, 1fr))',
    },
    gap: 2.25,
  },
  resultBox: {
    bgcolor: colors.background,
    border: `1px solid ${colors.accent}`,
    borderRadius: '16px',
    px: 3,
    py: 3.5,
    display: 'flex',
    flexDirection: 'column',
    gap: 1.75,
  },
  resultLabel: {
    textAlign: 'center',
    fontSize: '0.6875rem',
    fontWeight: 800,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: colors.muted,
  },
  resultValue: {
    textAlign: 'center',
    fontWeight: 900,
    fontSize: { xs: '2rem', sm: '2.75rem' },
    color: colors.accent,
    lineHeight: 1,
  },
  resultPeriod: {
    textAlign: 'center',
    fontSize: '0.75rem',
    fontWeight: 700,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    color: colors.muted,
  },
  resultDivider: {
    borderTop: `1px solid ${colors.line}`,
    my: 0.5,
  },
  resultSecondaryValue: {
    textAlign: 'center',
    fontWeight: 800,
    fontSize: '1.625rem',
    color: colors.text,
  },
  resultSecondaryLabel: {
    textAlign: 'center',
    fontSize: '0.75rem',
    fontWeight: 600,
    color: colors.muted,
  },
  summaryText: {
    textAlign: 'center',
    fontWeight: 700,
    fontSize: { xs: '0.9375rem', sm: '1.0625rem' },
    color: colors.text,
    maxWidth: '620px',
    mx: 'auto',
    mt: 3.5,
    lineHeight: 1.5,
  },
  breakdownGrid: {
    display: 'grid',
    gridTemplateColumns: {
      xs: '1fr',
      sm: 'repeat(3, minmax(0, 1fr))',
    },
    gap: 2,
    mt: 4,
  },
  breakdownItem: {
    bgcolor: colors.background,
    border: `1px solid ${colors.line}`,
    borderRadius: '12px',
    p: 2.5,
    textAlign: 'center',
  },
  breakdownIcon: {
    fontSize: '1.5rem',
  },
  breakdownValue: {
    fontWeight: 700,
    fontSize: '1.375rem',
    color: colors.text,
    mt: 0.75,
  },
  breakdownLabel: {
    fontSize: '0.8125rem',
    color: colors.muted,
    mt: 0.25,
  },
  quote: {
    textAlign: 'center',
    fontWeight: 700,
    fontSize: '1.125rem',
    color: colors.text,
    maxWidth: '560px',
    mx: 'auto',
    mt: 4,
    lineHeight: 1.5,
  },
  unlockWrap: {
    textAlign: 'center',
    mt: 4.5,
    pt: 4,
    borderTop: `1px solid ${colors.line}`,
  },
  unlockLabel: {
    fontWeight: 700,
    fontSize: '0.9375rem',
    color: colors.text,
    mb: 2,
  },
  unlockCta: {
    ...sharedStyles.primaryButton,
    textDecoration: 'none',
    display: 'inline-block',
  },
};

export const formStyles = {
  card: {
    maxWidth: '680px',
    mx: 'auto',
    bgcolor: colors.card,
    border: `1px solid ${colors.line}`,
    borderRadius: '20px',
    p: { xs: 3, sm: 5 },
  },
  title: {
    fontWeight: 800,
    fontSize: { xs: '1.375rem', sm: '1.625rem' },
    color: colors.text,
    textAlign: 'center',
    m: 0,
    mb: 3.5,
  },
  fieldsGrid: {
    display: 'grid',
    gridTemplateColumns: {
      xs: '1fr',
      sm: 'repeat(auto-fit, minmax(220px, 1fr))',
    },
    gap: 2.25,
  },
  hiddenGrid: {
    display: 'none',
  },
  errorBox: {
    bgcolor: colors.background,
    border: `1px solid ${colors.accent}`,
    color: colors.accent,
    fontSize: '0.8125rem',
    fontWeight: 600,
    px: 1.75,
    py: 1.25,
    borderRadius: '8px',
  },
  submitButton: {
    ...sharedStyles.primaryButton,
    mt: 0.75,
    width: '100%',
  },
};
