export const colors = {
  background: '#19181b',
  backgroundAlt: '#131215',
  card: '#242029',
  cardAlt: '#2b2530',
  line: 'rgba(255,255,255,0.08)',
  text: '#f5f4f7',
  textMuted: '#a5a1ab',
  textSoft: '#e8e6ea',
  accent: '#A3125B',
  accentLight: '#E1197E',
  accentGlow: 'rgba(225,25,126,0.28)',
  badgeBg: 'rgba(225,25,126,0.12)',
  badgeBorder: 'rgba(225,25,126,0.3)',
  overlay: 'rgba(10,9,11,0.72)',
  successBg: 'rgba(225,25,126,0.15)',
  errorText: '#d98a8a',
  errorOutline: '#d15b5b',
};

export const fonts = {
  body: 'Inter, system-ui, sans-serif',
  display: '"Space Grotesk", Inter, sans-serif',
};

export const sharedStyles = {
  container: {
    maxWidth: '1180px',
    px: { xs: 2.25, sm: 4 },
  },
  eyebrow: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 1,
    color: colors.accentLight,
    fontSize: '0.75rem',
    fontWeight: 700,
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
    fontFamily: fonts.body,
  },
  eyebrowDot: {
    width: 7,
    height: 7,
    borderRadius: '50%',
    bgcolor: colors.accent,
    boxShadow: `0 0 0 4px ${colors.accentGlow}`,
    flexShrink: 0,
  },
  primaryButton: {
    bgcolor: colors.accent,
    color: '#fff',
    borderRadius: '10px',
    px: { xs: 3.25, sm: 4.5 },
    py: { xs: 2.125, sm: 2.5 },
    fontSize: { xs: '0.9375rem', sm: '1.0625rem' },
    fontWeight: 800,
    letterSpacing: '0.02em',
    textTransform: 'uppercase',
    fontFamily: fonts.display,
    boxShadow: '0 14px 34px -8px rgba(200,31,110,0.55)',
    '&:hover': {
      bgcolor: colors.accentLight,
      boxShadow: '0 18px 40px -6px rgba(200,31,110,0.65)',
      transform: 'translateY(-2px)',
    },
    '&:disabled': {
      color: '#fff',
      opacity: 0.6,
    },
  },
  privacy: {
    mt: 1.25,
    textAlign: 'center',
    color: colors.textMuted,
    fontSize: '0.75rem',
    letterSpacing: '0.02em',
    fontFamily: fonts.body,
  },
  exampleBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    px: 0.875,
    py: 0.25,
    ml: 1,
    borderRadius: '6px',
    border: `1px solid ${colors.badgeBorder}`,
    bgcolor: colors.badgeBg,
    color: colors.accentLight,
    fontSize: '0.625rem',
    fontWeight: 700,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    verticalAlign: 'middle',
  },
};

export const pageStyles = {
  root: {
    minHeight: '100vh',
    bgcolor: colors.background,
    color: colors.text,
    fontFamily: fonts.body,
  },
  header: {
    position: 'sticky',
    top: 0,
    zIndex: 20,
    bgcolor: 'rgba(25,24,27,0.85)',
    backdropFilter: 'blur(10px)',
    borderBottom: `1px solid ${colors.line}`,
  },
  topBar: {
    ...sharedStyles.container,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    py: { xs: 1.75, sm: 2 },
  },
  brandRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 1.25,
  },
  logoIcon: {
    position: 'relative',
    width: 34,
    height: 34,
    borderRadius: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    overflow: 'hidden',
  },
  wordmark: {
    fontFamily: fonts.display,
    fontWeight: 700,
    fontSize: { xs: '1rem', sm: '1.1875rem' },
    letterSpacing: '-0.01em',
  },
  heroSection: {
    pt: { xs: 5.5, sm: 9.5 },
    pb: { xs: 4, sm: 7 },
    textAlign: 'center',
  },
  heroInner: {
    ...sharedStyles.container,
    maxWidth: '824px',
    mx: 'auto',
  },
  heroTitle: {
    mt: 2.5,
    mb: 2.75,
    fontFamily: fonts.display,
    fontWeight: 700,
    fontSize: { xs: '1.875rem', sm: '2.375rem', md: '3.375rem' },
    lineHeight: 1.08,
    letterSpacing: '-0.02em',
  },
  heroLead: {
    maxWidth: '600px',
    mx: 'auto',
    mb: 4,
    color: colors.textMuted,
    fontSize: { xs: '1rem', sm: '1.1875rem' },
    lineHeight: 1.6,
  },
  painList: {
    listStyle: 'none',
    p: 0,
    m: '0 auto 38px',
    maxWidth: '460px',
    display: 'flex',
    flexDirection: 'column',
    gap: 1.5,
    textAlign: 'left',
  },
  painItem: {
    display: 'flex',
    gap: 1.5,
    alignItems: 'flex-start',
    color: colors.textSoft,
    fontSize: '1rem',
    lineHeight: 1.5,
  },
  painItemIcon: {
    width: 22,
    height: 22,
    mt: '1px',
    borderRadius: '50%',
    bgcolor: 'rgba(255,255,255,0.06)',
    color: '#8b8791',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '0.75rem',
    fontWeight: 800,
    flexShrink: 0,
  },
  basedOn: {
    mt: 3.25,
    color: colors.textMuted,
    fontSize: '0.8125rem',
  },
  logoBar: {
    py: 4.25,
    borderTop: `1px solid ${colors.line}`,
    borderBottom: `1px solid ${colors.line}`,
  },
  tag: {
    display: 'inline-flex',
    alignItems: 'center',
    px: 1.25,
    py: 0.5,
    borderRadius: '999px',
    bgcolor: 'rgba(255,255,255,0.05)',
    border: `1px solid ${colors.line}`,
    color: colors.textMuted,
    fontSize: '0.6875rem',
    fontWeight: 700,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  logoStrip: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: { xs: 3, sm: 5.5 },
    flexWrap: 'wrap',
    opacity: 0.75,
  },
  logoChip: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    px: { xs: 1, sm: 1.5 },
    py: 0.5,
    minWidth: { xs: 110, sm: 140 },
    minHeight: 40,
  },
  logoImage: {
    display: 'block',
    maxWidth: { xs: '110px', sm: '340px' },
    maxHeight: '42px',
    width: 'auto',
    height: 'auto',
    objectFit: 'contain',
  },
  statsBar: {
    bgcolor: colors.cardAlt,
    borderTop: `1px solid ${colors.line}`,
    borderBottom: `1px solid ${colors.line}`,
  },
  statsGrid: {
    ...sharedStyles.container,
    display: 'grid',
    gridTemplateColumns: {
      xs: 'repeat(2, minmax(0, 1fr))',
      md: 'repeat(4, minmax(0, 1fr))',
    },
    gap: { xs: 1.75, sm: 2.5 },
  },
  statItem: {
    py: { xs: 3, sm: 4.75 },
    px: { xs: 1, sm: 1.75 },
    textAlign: 'center',
  },
  statNum: {
    fontFamily: fonts.display,
    fontWeight: 700,
    fontSize: { xs: '2rem', sm: '2.5rem' },
    color: colors.accentLight,
    letterSpacing: '-0.01em',
  },
  statLabel: {
    mt: 1,
    color: colors.textMuted,
    fontSize: '0.84375rem',
    lineHeight: 1.4,
  },
  section: {
    py: { xs: 7.5, sm: 11 },
  },
  sectionHead: {
    maxWidth: '640px',
    mx: 'auto',
    mb: 5,
    textAlign: 'center',
  },
  sectionTitle: {
    mt: 2,
    mb: 1.75,
    fontFamily: fonts.display,
    fontWeight: 700,
    fontSize: { xs: '1.625rem', sm: '2rem' },
    lineHeight: 1.15,
    letterSpacing: '-0.01em',
  },
  testimonialGrid: {
    display: 'grid',
    // gridTemplateColumns: {
    //   xs: '1fr',
    //   md: 'repeat(3, minmax(0, 1fr))',
    // },
    gap: { xs: 2, sm: 2.75 },
  },
  testimonialCard: {
    height: '100%',
    bgcolor: colors.card,
    border: `1px solid ${colors.line}`,
    borderRadius: '16px',
    boxShadow: 'none',
  },
  testimonialCardContent: {
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    p: 3.25,
    '&:last-child': {
      pb: 3.25,
    },
  },
  testimonialQuote: {
    color: colors.textSoft,
    fontSize: '0.9375rem',
    lineHeight: 1.6,
  },
  testimonialAuthor: {
    mt: 'auto',
    display: 'flex',
    alignItems: 'center',
    gap: 1.5,
    pt: 2.25,
  },
  avatar: {
    width: 42,
    height: 42,
    background: `linear-gradient(135deg, ${colors.accentLight}, #6b1a45)`,
    flexShrink: 0,
  },
  testimonialName: {
    fontWeight: 700,
    fontSize: '0.875rem',
    color: colors.text,
  },
  testimonialRole: {
    fontSize: '0.78125rem',
    color: colors.textMuted,
  },
  finalCta: {
    py: { xs: 8, sm: 12 },
    textAlign: 'center',
  },
  finalTitle: {
    mt: 2,
    mb: 2,
    maxWidth: '680px',
    mx: 'auto',
    fontFamily: fonts.display,
    fontWeight: 700,
    fontSize: { xs: '1.625rem', sm: '2.375rem' },
    lineHeight: 1.15,
  },
  finalDescription: {
    maxWidth: '520px',
    mx: 'auto',
    mb: 3.75,
    color: colors.textMuted,
    fontSize: '1rem',
    lineHeight: 1.6,
  },
  footer: {
    px: 4,
    py: 4,
    borderTop: `1px solid ${colors.line}`,
    textAlign: 'center',
    color: colors.textMuted,
    fontSize: '0.8125rem',
  },
};

export const modalStyles = {
  dialogPaper: {
    width: '100%',
    maxWidth: '460px',
    borderRadius: '18px',
    bgcolor: colors.card,
    color: colors.text,
    border: `1px solid ${colors.line}`,
    boxShadow: '0 30px 70px -20px rgba(0,0,0,0.6)',
    backgroundImage: 'none',
  },
  backdrop: {
    bgcolor: colors.overlay,
    backdropFilter: 'blur(3px)',
  },
  closeButton: {
    position: 'absolute',
    top: 16,
    right: 16,
    width: 34,
    height: 34,
    borderRadius: '50%',
    bgcolor: 'rgba(255,255,255,0.06)',
    border: `1px solid ${colors.line}`,
    color: colors.text,
    '&:hover': {
      bgcolor: 'rgba(255,255,255,0.12)',
    },
  },
  content: {
    px: { xs: 2.75, sm: 4.25 },
    py: { xs: 3.25, sm: 4.25 },
  },
  title: {
    mb: 0.75,
    fontFamily: fonts.display,
    fontWeight: 700,
    fontSize: '1.375rem',
  },
  subtitle: {
    mb: 3,
    color: colors.textMuted,
    fontSize: '0.875rem',
  },
  textField: {
    '& .MuiFormLabel-root': {
      color: '#c9c4cf',
      fontSize: '0.8125rem',
      fontWeight: 600,
    },
    '& .MuiOutlinedInput-root': {
      bgcolor: colors.backgroundAlt,
      color: colors.text,
      borderRadius: '9px',
      '& fieldset': {
        borderColor: colors.line,
      },
      '&:hover fieldset': {
        borderColor: colors.badgeBorder,
      },
      '&.Mui-focused fieldset': {
        borderColor: colors.accentLight,
        borderWidth: 2,
      },
      '&.Mui-error fieldset': {
        borderColor: colors.errorOutline,
      },
    },
    '& .MuiInputBase-input': {
      fontSize: '0.90625rem',
      fontFamily: fonts.body,
    },
    '& .MuiSvgIcon-root': {
      color: colors.textMuted,
    },
    '& .MuiFormHelperText-root': {
      mx: 0,
      mt: 0.625,
      color: colors.errorText,
      fontSize: '0.75rem',
    },
  },
  phoneRow: {
    display: 'flex',
    gap: 1,
    alignItems: 'flex-start',
  },
  phoneCodeField: {
    flex: '0 0 118px',
  },
  phoneNumberField: {
    flex: 1,
    minWidth: 0,
  },
  successWrap: {
    py: 1.25,
    px: 0.5,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    gap: 1.75,
  },
  successCheck: {
    width: 56,
    height: 56,
    borderRadius: '50%',
    bgcolor: colors.successBg,
    color: colors.accentLight,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
};
